### ISSUE TITLE
Bad result!!

### ISSUE THREAD

**Issue by linVdcd** [1adrianb/2D-and-3D-face-alignment#27]
The 2D-FAN-300W.t7 model get a bad result! However,the pytorch version is good.
![2018-01-17 11-22-26](https://user-images.githubusercontent.com/8973153/35024247-59cbd0b0-fb79-11e7-92fd-a05bf42d6328.png)

**Comment by 1adrianb** [comment]
Hi @linVdcd 
For best results on large poses you should use the 2D-FAN.t7 (so the non 300W version). The python code is using by default a) the non-300W version b) is using the CNN-based dlib face detector, tho in general as suggested previously a better CNN based detector should be used.

Please use the search function since I  replied to similar or near-identical questions previously and offered solutions for improvments.
